"""initial lux_monitor schema

Revision ID: a273c0ee43c1
Revises: 
Create Date: 2026-05-29 08:18:25.445136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a273c0ee43c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal', sa.String(length=32), nullable=False),
    sa.Column('portal_listing_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('commune', sa.String(length=128), nullable=False),
    sa.Column('address_text', sa.String(length=512), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('listing_type', sa.String(length=8), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('rooms_total', sa.Integer(), nullable=True),
    sa.Column('surface_m2', sa.Float(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('has_garage', sa.Boolean(), nullable=False),
    sa.Column('parking_spaces', sa.Integer(), nullable=False),
    sa.Column('has_garden', sa.Boolean(), nullable=False),
    sa.Column('garden_m2', sa.Float(), nullable=True),
    sa.Column('has_balcony_terrace', sa.Boolean(), nullable=False),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('renovation_year', sa.Integer(), nullable=True),
    sa.Column('rent_eur', sa.Float(), nullable=True),
    sa.Column('charges_eur', sa.Float(), nullable=True),
    sa.Column('rent_total_eur', sa.Float(), nullable=True),
    sa.Column('deposit_months', sa.Integer(), nullable=True),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.Column('price_per_m2_eur', sa.Float(), nullable=True),
    sa.Column('energy_class', sa.String(length=2), nullable=True),
    sa.Column('thermal_class', sa.String(length=2), nullable=True),
    sa.Column('annual_energy_cost_eur', sa.Integer(), nullable=True),
    sa.Column('taxe_fonciere_eur', sa.Float(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_lang', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('photos_urls', sa.JSON(), nullable=False),
    sa.Column('listing_agency', sa.String(length=256), nullable=True),
    sa.Column('drive_time_rush_min', sa.Integer(), nullable=True),
    sa.Column('pt_time_rush_min', sa.Integer(), nullable=True),
    sa.Column('walk_to_school_min', sa.Integer(), nullable=True),
    sa.Column('walk_to_creche_min', sa.Integer(), nullable=True),
    sa.Column('walk_to_park_min', sa.Integer(), nullable=True),
    sa.Column('llm_quality_score', sa.Integer(), nullable=True),
    sa.Column('llm_red_flags', sa.JSON(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('price_history', sa.JSON(), nullable=False),
    sa.Column('user_shortlist', sa.Boolean(), nullable=False),
    sa.Column('user_viewing_scheduled', sa.DateTime(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal', 'portal_listing_id', name='uq_portal_listing')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('ix_listings_commune', ['commune'], unique=False)
        batch_op.create_index('ix_listings_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_listings_listing_type', ['listing_type'], unique=False)
        batch_op.create_index('ix_listings_portal', ['portal'], unique=False)

    op.create_table('price_history_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.Column('charges_eur', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_entries_listing_id'), ['listing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_entries_listing_id'))

    op.drop_table('price_history_entries')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_portal')
        batch_op.drop_index('ix_listings_listing_type')
        batch_op.drop_index('ix_listings_is_active')
        batch_op.drop_index('ix_listings_commune')

    op.drop_table('listings')
    # ### end Alembic commands ###
