"""add duplicate_of_id to listings

Revision ID: d2218c88bfbc
Revises: eae5e3f48442
Create Date: 2026-05-29 09:28:43.448944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2218c88bfbc'
down_revision: Union[str, None] = 'eae5e3f48442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_listings_duplicate_of_id'), ['duplicate_of_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_duplicate_of_id'))
        batch_op.drop_column('duplicate_of_id')

    # ### end Alembic commands ###
