"""add legacy DE/FR schema (enum-decoupled)

Revision ID: fc0644c9e210
Revises: a273c0ee43c1
Create Date: 2026-05-29 08:29:48.791105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0644c9e210'
down_revision: Union[str, None] = 'a273c0ee43c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('listing_type', sa.String(length=10), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('avg_price_per_sqm', sa.Float(), nullable=True),
    sa.Column('median_price_per_sqm', sa.Float(), nullable=True),
    sa.Column('total_listings', sa.Integer(), nullable=True),
    sa.Column('new_listings_this_week', sa.Integer(), nullable=True),
    sa.Column('removed_listings_this_week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_date_country', ['snapshot_date', 'country', 'listing_type', 'property_type'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('listing_type', sa.Enum('rent', 'buy', name='listing_type_enum'), nullable=False),
    sa.Column('property_type', sa.Enum('apartment', 'house', 'land', name='property_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_per_sqm', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Float(), nullable=True),
    sa.Column('living_area_sqm', sa.Float(), nullable=True),
    sa.Column('plot_area_sqm', sa.Float(), nullable=True),
    sa.Column('address_city', sa.String(length=255), nullable=True),
    sa.Column('address_postal_code', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('energy_rating', sa.String(length=10), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('has_garden', sa.Boolean(), nullable=True),
    sa.Column('has_garage', sa.Boolean(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('listing_url', sa.String(length=1000), nullable=False),
    sa.Column('contact_info', sa.String(length=500), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index('ix_address_postal_code', ['address_postal_code'], unique=False)
        batch_op.create_index('ix_country_listing_type', ['country', 'listing_type'], unique=False)
        batch_op.create_index('ix_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_source_external_id', ['source', 'external_id'], unique=True)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('listings_found', sa.Integer(), nullable=True),
    sa.Column('new_listings', sa.Integer(), nullable=True),
    sa.Column('updated_listings', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='run_status_enum'), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_property_id', ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_property_id')

    op.drop_table('price_history')
    op.drop_table('scrape_runs')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index('ix_source_external_id')
        batch_op.drop_index('ix_is_active')
        batch_op.drop_index('ix_country_listing_type')
        batch_op.drop_index('ix_address_postal_code')

    op.drop_table('properties')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_date_country')

    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
